### ISSUE TITLE
VirtualBox Guest additions error

### ISSUE THREAD

**Issue by mfuxi** [kerneltlv/kernel-hacking#12]
I'm using Fedora 27 workstation
Installed the latest virtualbox 5.2.7
Installed the latest vagrant 2.0.2
After `vagrant up` virtualbox is trying to install 5.2.7 guest additions and then I see these errors:

`VirtualBox Guest Additions: modprobe vboxsf failed
An error occurred during installation of VirtualBox Guest Additions 5.2.7. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Job for vboxadd-service.service failed because the control process exited with error code.
See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
`

**Comment by idoby** [comment]
Hi! Thanks for trying out the project. Do you have enough disk space?

**Comment by idoby** [comment]
Hi, thanks for trying out the project. I upgraded Debian to 9.3, so it should be okay now. I was using an outdated version of VirtualBox.

Please pull the latest commits, rebuild the box and report your findings please.

**Comment by mfuxi** [comment]
Hi, 
It's working now!
I rebuilt the box and managed to compile the kernel using: `khack kernel make`

Thanks!

**Comment by idoby** [comment]
Thanks for reporting!
